DROP POLICY IF EXISTS payments_own ON public.payments;
DROP POLICY IF EXISTS payments_select ON public.payments;
DROP POLICY IF EXISTS payments_insert ON public.payments;
DROP POLICY IF EXISTS payments_update ON public.payments;
DROP POLICY IF EXISTS payments_delete ON public.payments;
CREATE POLICY payments_select ON public.payments FOR SELECT TO authenticated USING (created_by_id=auth.uid() OR user_id=auth.uid()::text OR public.is_admin());
CREATE POLICY payments_insert ON public.payments FOR INSERT TO authenticated WITH CHECK ((created_by_id=auth.uid() OR user_id=auth.uid()::text) AND COALESCE(status,'pending') NOT IN ('succeeded','refunded'));
CREATE POLICY payments_update ON public.payments FOR UPDATE TO authenticated USING (created_by_id=auth.uid() OR user_id=auth.uid()::text OR public.is_admin()) WITH CHECK (public.is_admin() OR ((created_by_id=auth.uid() OR user_id=auth.uid()::text) AND COALESCE(status,'pending') NOT IN ('succeeded','refunded')));
CREATE POLICY payments_delete ON public.payments FOR DELETE TO authenticated USING (created_by_id=auth.uid() OR user_id=auth.uid()::text OR public.is_admin());
DROP POLICY IF EXISTS hire_apps_update ON public.hire_applications;
CREATE POLICY hire_apps_update ON public.hire_applications FOR UPDATE TO authenticated USING (public.is_admin() OR created_by_id=auth.uid() OR worker_id=auth.uid()::text OR EXISTS (SELECT 1 FROM public.hire_jobs j WHERE j.id::text=hire_applications.hire_job_id AND (j.created_by_id=auth.uid() OR j.customer_id=auth.uid()::text))) WITH CHECK (public.is_admin() OR EXISTS (SELECT 1 FROM public.hire_jobs j WHERE j.id::text=hire_applications.hire_job_id AND (j.created_by_id=auth.uid() OR j.customer_id=auth.uid()::text)) OR ((created_by_id=auth.uid() OR worker_id=auth.uid()::text) AND COALESCE(status,'pending') IN ('pending','withdrawn','rejected')));
DROP POLICY IF EXISTS notifications_own ON public.notifications;
DROP POLICY IF EXISTS notifications_select ON public.notifications;
DROP POLICY IF EXISTS notifications_insert ON public.notifications;
DROP POLICY IF EXISTS notifications_update ON public.notifications;
DROP POLICY IF EXISTS notifications_delete ON public.notifications;
CREATE POLICY notifications_select ON public.notifications FOR SELECT TO authenticated USING (user_id=auth.uid()::text OR created_by_id=auth.uid() OR public.is_admin());
CREATE POLICY notifications_insert ON public.notifications FOR INSERT TO authenticated WITH CHECK (user_id=auth.uid()::text AND created_by_id=auth.uid());
CREATE POLICY notifications_update ON public.notifications FOR UPDATE TO authenticated USING (user_id=auth.uid()::text OR public.is_admin()) WITH CHECK (user_id=auth.uid()::text OR public.is_admin());
CREATE POLICY notifications_delete ON public.notifications FOR DELETE TO authenticated USING (user_id=auth.uid()::text OR created_by_id=auth.uid() OR public.is_admin());
DROP POLICY IF EXISTS messages_own ON public.marketplace_messages;
DROP POLICY IF EXISTS messages_select ON public.marketplace_messages;
DROP POLICY IF EXISTS messages_insert ON public.marketplace_messages;
DROP POLICY IF EXISTS messages_update ON public.marketplace_messages;
DROP POLICY IF EXISTS messages_delete ON public.marketplace_messages;
CREATE POLICY messages_select ON public.marketplace_messages FOR SELECT TO authenticated USING (sender_id=auth.uid()::text OR recipient_id=auth.uid()::text OR created_by_id=auth.uid() OR public.is_admin());
CREATE POLICY messages_insert ON public.marketplace_messages FOR INSERT TO authenticated WITH CHECK (sender_id=auth.uid()::text AND created_by_id=auth.uid());
CREATE POLICY messages_update ON public.marketplace_messages FOR UPDATE TO authenticated USING (sender_id=auth.uid()::text OR recipient_id=auth.uid()::text OR public.is_admin()) WITH CHECK (public.is_admin() OR sender_id=auth.uid()::text OR recipient_id=auth.uid()::text);
CREATE POLICY messages_delete ON public.marketplace_messages FOR DELETE TO authenticated USING (sender_id=auth.uid()::text OR created_by_id=auth.uid() OR public.is_admin());
DROP POLICY IF EXISTS activity_read ON public.activity_events;
CREATE POLICY activity_read ON public.activity_events FOR SELECT TO authenticated USING (created_by_id=auth.uid() OR public.is_admin());