UPDATE storage.buckets SET public=false WHERE id='titanos-uploads';
DROP POLICY IF EXISTS titanos_uploads_read ON storage.objects;
DROP POLICY IF EXISTS titanos_uploads_insert ON storage.objects;
DROP POLICY IF EXISTS titanos_uploads_delete ON storage.objects;
DROP POLICY IF EXISTS titanos_uploads_select_own ON storage.objects;
DROP POLICY IF EXISTS titanos_uploads_select_public ON storage.objects;
DROP POLICY IF EXISTS titanos_uploads_insert_own ON storage.objects;
DROP POLICY IF EXISTS titanos_uploads_delete_own ON storage.objects;
CREATE POLICY titanos_uploads_select_own ON storage.objects FOR SELECT TO authenticated USING (bucket_id='titanos-uploads' AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY titanos_uploads_select_public ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id='titanos-uploads' AND (storage.foldername(name))[1]='public');
CREATE POLICY titanos_uploads_insert_own ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id='titanos-uploads' AND ((storage.foldername(name))[1]=auth.uid()::text OR ((storage.foldername(name))[1]='public' AND (storage.foldername(name))[2]=auth.uid()::text)));
CREATE POLICY titanos_uploads_delete_own ON storage.objects FOR DELETE TO authenticated USING (bucket_id='titanos-uploads' AND ((storage.foldername(name))[1]=auth.uid()::text OR ((storage.foldername(name))[1]='public' AND (storage.foldername(name))[2]=auth.uid()::text) OR owner=auth.uid()));
CREATE INDEX IF NOT EXISTS idx_hire_applications_job ON public.hire_applications(hire_job_id);
CREATE INDEX IF NOT EXISTS idx_hire_applications_worker ON public.hire_applications(worker_id);
CREATE INDEX IF NOT EXISTS idx_hire_jobs_status_created ON public.hire_jobs(status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_messages_hire_job ON public.marketplace_messages(hire_job_id);
CREATE INDEX IF NOT EXISTS idx_payments_external_id ON public.payments(external_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON public.notifications(user_id,created_at DESC);
COMMENT ON TABLE public.beta_signups IS 'Anon INSERT allowed for marketing; rate-limit at edge/WAF.';