create table if not exists public.titan_ai_knowledge (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  domain text not null default 'general',
  title text not null,
  content text not null,
  tags text[] not null default '{}'::text[],
  source text not null default 'titanos',
  quality_score numeric(4,3) not null default 0.900 check (quality_score >= 0 and quality_score <= 1),
  enabled boolean not null default true,
  search_document tsvector not null default ''::tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.titan_ai_knowledge_search_document()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.search_document :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(array_to_string(new.tags, ' '), '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.content, '')), 'C');
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists titan_ai_knowledge_search_document_trg on public.titan_ai_knowledge;
create trigger titan_ai_knowledge_search_document_trg
before insert or update of title, content, tags
on public.titan_ai_knowledge
for each row execute function public.titan_ai_knowledge_search_document();

create index if not exists titan_ai_knowledge_search_idx
  on public.titan_ai_knowledge using gin (search_document);
create index if not exists titan_ai_knowledge_domain_enabled_idx
  on public.titan_ai_knowledge (domain, enabled, quality_score desc);

alter table public.titan_ai_knowledge enable row level security;
revoke all on table public.titan_ai_knowledge from anon, authenticated;
revoke all on sequence public.titan_ai_knowledge_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.titan_ai_knowledge to service_role;
grant usage, select on sequence public.titan_ai_knowledge_id_seq to service_role;
revoke all on function public.titan_ai_knowledge_search_document() from public, anon, authenticated;
grant execute on function public.titan_ai_knowledge_search_document() to service_role;

insert into public.titan_ai_knowledge (slug, domain, title, content, tags, source, quality_score)
values
('titanos-operating-model','platform','TitanOS operating model','TitanOS is an operating system for field work. Recommendations prioritize safety and trust, revenue quality, reliability, and speed of execution.','{titanos,platform,operations}','titanos_core',1.000),
('second-me-model','ai','2nd Me operating model','2nd Me follows: observe or remember, understand the situation, infer intent, present the right interface, request appropriate permission, act, and learn. It must not silently execute writes.','{2nd-me,ai,memory,permissions}','titanos_core',1.000),
('jobs-workflow','jobs','Jobs workflow','Jobs are managed from Jobs and Schedule. Titan AI may propose or confirm schedule_job actions, but live writes must remain authenticated, authorized, tenant-scoped, and confirmation-gated.','{jobs,schedule,dispatch}','titanos_core',0.990),
('customer-workflow','customers','Customer workflow','Customer records belong to the signed-in owner or authorized tenant. Titan AI can help create customers and use current customer context, but must never invent a customer that is not in provided data.','{customers,crm,tenant}','titanos_core',0.990),
('invoice-workflow','money','Invoice workflow','Invoices support draft, sent, unpaid, partial, overdue, and paid-style states. Titan AI can draft or mark supported invoice actions only through the approved action path and must distinguish outstanding balances from collected revenue.','{invoice,billing,accounts-receivable,money}','titanos_core',0.990),
('estimate-workflow','money','Estimate workflow','Estimates are pre-invoice job proposals. Titan AI can prepare a create_estimate action from supplied customer, scope, and amount information, with confirmation before persistence.','{estimate,quote,money}','titanos_core',0.980),
('expense-workflow','money','Expense workflow','Expenses feed margin and reporting. Titan AI can record an expense after obtaining a valid amount and should preserve category, vendor, date, deductibility, and business-use context when supplied.','{expense,tax,margin,money}','titanos_core',0.980),
('driver-hub','driver','Driver Hub','Driver Hub covers active driving work, trip tracking, operational metrics, mileage, job movement, and driver-focused workflows. Location and driver records must stay user-scoped and permission-aware.','{driver,driver-hub,gps,mileage,trips}','titanos_core',0.980),
('invisible-interface','ai','Invisible Interface','When a user is comparing, deciding, reviewing, planning, or supplying structured information, Titan AI should prefer a temporary fit-for-purpose interface such as a comparison, checklist, metrics view, decision card, or form when available.','{invisible-interface,ui,decision,forms}','titanos_core',1.000),
('memory-trust','ai','Titan memory trust rules','Durable memory is authorized remembered context, not automatically a current authoritative record. If memory conflicts with a current authoritative business record, prefer the current record and disclose the conflict.','{memory,trust,grounding}','titanos_core',1.000),
('knowledge-grounding','ai','Titan knowledge grounding','Titan platform knowledge explains how TitanOS works. It must not be presented as user account data. Account-specific claims must come from authenticated server-owned snapshots or authorized durable memory.','{knowledge,rag,grounding}','titanos_core',1.000),
('action-safety','security','Titan AI action safety','Write actions require allowed intents, authorization, confirmation or an explicitly approved automation mode, idempotency where applicable, and rollback or compensating behavior where supported. The kill switch blocks AI writes.','{security,actions,confirmation,rollback,idempotency}','titanos_core',1.000)
on conflict (slug) do update set
  domain = excluded.domain,
  title = excluded.title,
  content = excluded.content,
  tags = excluded.tags,
  source = excluded.source,
  quality_score = excluded.quality_score,
  enabled = true;
