-- TitanOS 2.0 / 5000X: public contract bearer-token hardening
-- Preserve existing links by hashing their current raw token before clearing it.
-- New raw tokens are generated by authenticated server code and never stored.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.contracts
  ADD COLUMN IF NOT EXISTS share_token_hash text;

UPDATE public.contracts
SET share_token_hash = encode(digest(share_token, 'sha256'), 'hex')
WHERE share_token IS NOT NULL
  AND length(share_token) BETWEEN 32 AND 256
  AND (share_token_hash IS NULL OR share_token_hash = '');

UPDATE public.contracts
SET share_token = NULL
WHERE share_token_hash IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_contracts_share_token_hash
  ON public.contracts (share_token_hash)
  WHERE share_token_hash IS NOT NULL;

COMMENT ON COLUMN public.contracts.share_token_hash IS
  'SHA-256 hash of the public contract bearer token. Raw signing tokens must never be stored.';

-- Public contract access now goes through rate-limited serverless endpoints.
REVOKE EXECUTE ON FUNCTION public.get_public_contract_by_share_token(text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sign_public_contract_by_share_token(text, text, text) FROM PUBLIC, anon, authenticated;

DROP FUNCTION IF EXISTS public.get_contract_by_share_token(text);
DROP FUNCTION IF EXISTS public.sign_contract_by_share_token(text, text, text);
